title: 'National Library Board'
description: 'Eye on Asia is a collaborative effort by the National Library, Singapore with partners such as Enterprise Singapore, Business China Singapore to provide resources for everyone, including young Singaporeans who wish to find out more about the region and explore internationalisation opportunities abroad. Focusing on ASEAN countries, China and India including emerging cities, you will discover a broad overview of useful resources to help you be more aware of developments in these countries as Singapore gears itself for the future economy.'
url: 'https://www.eyeonasia.gov.sg'
google_analytics: UA-50449401-26
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: events
paginate: 12
paginate_path: '/events/page:num'
is_government: false
favicon: /images/favicon-eoa.png
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page

colors:
  primary-color: '#2D3436'
  secondary-color: '#C20e11'
  media-colors:
    - title: media-color-one
      color: '#2d3436'
    - title: media-color-two
      color: '#e21216'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
staging: https://nlb-eoa-staging.netlify.com
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
